name: Set up
description: Set up Node and dependencies

runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "20"
    - name: Install dependencies
      run: npm install
      shell: bash
