name: Prettier

on:
  push:
    branches:
      - "*"

jobs:
  prettier:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SetUp
        uses: ./.github/actions/setUp

      - name: Run Prettier
        run: npm run format --list-different
